- recipes/server_install.rb
- recipes/server_os_packages.rb
Hi i think the correct platform family for ubuntu would be debian.
> change platform_family ubuntu to debian

- providers/idomysqlconnection.rb
- providers/idopgsqlconnection.rb
seems its typos. converge doesn't work
> fix typos in lwrp

- resources/externalcommandlistener.rb
- templates/default/object.externalcommandlistener.conf.erb
> fix typos and template

- providers/endpoint.rb
this patch allow to converge cookbook in Test Kitchen. Lets fix all other object the same way.
> add test kitchen support

- providers/zone.rb
- resources/zone.rb
- templates/default/object.zone.conf.erb
this PR allow to add section 
```
object Zone "global-templates" {
global = true
}
```
to zone objects.
> allow global-templates for zone object

- .kitchen.yml
- Berksfile
- attributes/default.rb
- attributes/repo.rb
- attributes/server_apache.rb
- attributes/server_classic_ui.rb
- libraries/search.rb
- recipes/core_install.rb
- recipes/server_apache.rb
- test/cookbooks/icinga2-test/metadata.rb
- test/cookbooks/icinga2-test/recipes/default.rb
- test/integration/web2/serverspec/web2_spec.rb
First off: thank you for this amazing cookbook, it's been a great help to us!
This pull request will:
* add a test suite for icingaweb2
* add debian wheezy as a platform to test
* fix some quirks I had with setting up icingaweb2 on the given platforms (ran into some problems on debian and ubuntu with apt keys, mismatching versions, missing nagios user, ...)
More details in the separate commits. Let me know if I need to change anything.
~~ps: I tried creating an account on https://accounts.icinga.org to open a bug issue (as directed in README.md) but I never received the e-mail with validation code. I tried with 2 different mail addresses and tried revalidating both (accounts named Zhann and Zhann_) but no luck. So my apologies for the direct pull request.~~
EDIT: Issue …
> add web2 suite and fix web2 on all platforms

- resources/applyservice.rb
https://dev.icinga.org/issues/9405
> Allows underscores in set attribute

- spec/spec_helper.rb
- spec/support/matchers.rb
Added some "basic" chefspec matchers for every resource to allow easy testing.
> Add chefspec matchers

- libraries/icinga2.rb
- This fixes the rubocop errors
https://jenkins-01.eastus.cloudapp.azure.com/job/icinga2-cookbook/lastFailedBuild/console
> Rubocop fixes

- .gitignore
- CONTRIBUTING.md
- README.md
https://dev.icinga.org/issues/12280
> Adds CONTRIBUTING.md

- .kitchen.yml
- test/cookbooks/icinga2-test/recipes/default.rb
- test/integration/client/serverspec/client_spec.rb
- test/integration/client/serverspec/spec_helper.rb
- test/integration/server/serverspec/server_spec.rb
- test/integration/server/serverspec/spec_helper.rb
- test/integration/web2/serverspec/spec_helper.rb
- test/integration/web2/serverspec/web2_spec.rb
Centos testing is not included because of a known authentication issue: https://github.com/mitchellh/vagrant/issues/7627
We need to do some work on version handling, this breaks some Debian and Ubuntu versions. That's why I left them out temporarly.
Anyways, this should be a good base to start with
> Update integration testing

- .rubocop.yml
https://dev.icinga.org/issues/12942
> Ignore rubocop BlockLenth

- libraries/provider_instance.rb
- libraries/resource_apilistener.rb
- libraries/resource_applydependency.rb
- libraries/resource_applynotification.rb
- libraries/resource_applyservice.rb
- libraries/resource_checkcommand.rb
- libraries/resource_endpoint.rb
- libraries/resource_eventcommand.rb
- libraries/resource_host.rb
- libraries/resource_hostgroup.rb
- libraries/resource_notification.rb
- libraries/resource_notificationcommand.rb
- libraries/resource_scheduleddowntime.rb
- libraries/resource_service.rb
- libraries/resource_servicegroup.rb
- libraries/resource_timeperiod.rb
- libraries/resource_user.rb
- libraries/resource_usergroup.rb
- libraries/resource_zone.rb
Makes wrapping possible of the object templates that belong to
Icinga2Instance resources, as is already possible for the
Icinga2Environment resource.
> Makes it possible to wrap the template of Icinga2Instance resources.

- libraries/provider_instance.rb
This is a simple fix for #234 that worked well for me.
> Fix NoMethodError in provider_instance

- attributes/default.rb
- attributes/repo.rb
- attributes/server_apache.rb
- attributes/server_classic_ui.rb
I'm not sure if adding support for raspbian is something you guys are considering, but given that I needed it for a project of mine I figured I'd just go ahead and issue a pull request.
For this to work one needs to compile a current ruby from source or get a more recent version from the stretch packages. Once that is sorted getting icinga to run on the raspberry is a piece of cake :)
Please note that I did not test the classic_ui part!
> Add raspbian support

- README.md
The original request for this feature can be found in this issue
https://github.com/Icinga/chef-icinga2/issues/152
The Original Commit for this addition before it was closed is found here
https://github.com/Icinga/chef-icinga2/commit/33ab922012b6cf826402b3c16e61f318263c4ad1
This is an update to make the feature actually work as intended in the Documentation.
Let me know if you have any questions.
> [Fix] Wrong Attribute in Documentation

- README.md
- libraries/provider_instance.rb
- libraries/resource_apiuser.rb
- spec/support/matchers.rb
- templates/default/object.apiuser.conf.erb
Hi, this PR add new ApiUser object https://www.icinga.com/docs/icinga2/latest/doc/09-object-types/#apiuser
> Add ApiUser object

- metadata.rb
Updated to latest chocolatey dependency.
> updated chocolatey dependency

- README.md
- libraries/resource_influxdbwriter.rb
- spec/support/matchers.rb
- templates/default/object.influxdbwriter.conf.erb
This PR adds [InfluxdbWriter](https://www.icinga.com/docs/icinga2/latest/doc/09-object-types/#influxdbwriter) object support.
> Add influxdbwriter object LWRP

- attributes/default.rb
- attributes/repo.rb
* Fix el7 package suffix
* Update icinga2 version
> Fix el7 package suffix
