Icinga/chef-icinga2

- attributes/default.rb
- recipes/server.rb
Bug report
Ubuntu 14.04 kitchen tests:
Ubuntu: Server installatoin fails because apt_package[php5]fails.
* apt_package[php5] action install [2015-01-16T10:12:47+00:00] INFO: Processing apt_package[php5] action install (icinga2::server_os_packages line 29)
================================================================================
Error executing action `install` on resource 'apt_package[php5]'
================================================================================
Possible fix would be to include apt recipe.
Ubuntu: 
* template[/etc/icinga2/icinga2.conf] action create[2015-01-16T10:22:29+00:00] INFO: Processing template[/etc/icinga2/icinga2.conf] action create (icinga2::server_core line 61)       
* cannot determine user id for 'icinga', does the user exist on this system? …
> Fixes for ubuntu server installation

- attributes/repo.rb
For CentOS 6 platform_version return '6.6' but packages in official repo has release '1-el6' like "icinga2-2.2.3-1.el6.x86_64"
This patch fix this problem.
> fix package version for release repo

- recipes/server_ido_schema.rb
Executing the command using "EOH" did always write an "\n" after the command. Using inverted commas is working better for me. Also, the command for psql is executed with the user "postgres" which doesn't have write permissions for "/etc/icinga/". 
I tested server_ido_schema.rb on centos 6.5 with a postgres database and it worked for me.
> Typos and bugs

- attributes/default.rb
- templates/default/icinga2.conf.erb
include repository.d is not used for the many types of icinga2 installations, ex: cluster with separate satellites, one server installations, etc. This PR allow for disabling repository.d. Disabling of unnecessary catalogs will simplify icinga2.conf and debugging problems.
> add attribute for disabling repository.d

- recipes/server_core.rb
- templates/default/icinga2.conf.erb
this PR allow to disable creation dir 'user_defined_objects_dir' and include in icinga2.conf. This allows for more fine-tune the configuration file.
> allow to disable user_defined_objects_dir

- attributes/server_apache.rb
Let's use a greater-than operator. This will only work with Chef-Client 12! I noticed this in the release notes of chef-client 12.
"value_for_platform method in the Recipe DSL supports version constraints Version constraints—>, <, >=, <=, ~>—may be used when specifying a version. An exception is raised if two version constraints match. An exact match will always take precedence over a match made from a version constraint."
> Version constrain bug for centos newer than 7.0

- attributes/server_apache.rb
Same bug as in pull #24. Chef seems to be buggy here, but thats easy to check:
```bash
[vagrant@default-centos-70 ~]$ chef-apply -e "log value_for_platform(%w(centos redhat fedora) => { '>= 7.0' => %w(7),'default' => %w(default) })"
Recipe: (chef-apply cookbook)::(chef-apply recipe)
* log[7] action write
[vagrant@default-centos-70 ~]$ chef-apply -e "log value_for_platform(%w(centos redhat fedora) => { '>= 7' => %w(7),'default' => %w(default) })"
Recipe: (chef-apply cookbook)::(chef-apply recipe)
* log[default] action write
[vagrant@default-centos-70 ~]$ chef-apply -e "log value_for_platform(%w(centos redhat fedora) => { '>= 6.0' => %w(7),'default' => %w(default) })"
Recipe: (chef-apply cookbook)::(chef-apply recipe)
* log[7] action write
```
> Fix version contraint for centos 7 apache modules

- README.md
- providers/applyservice.rb
- resources/applyservice.rb
- templates/default/object.applyservice.conf.erb
Closes [9366](https://dev.icinga.org/issues/9366).
Adds the ability to write an 'apply Service for'.
The way it works, is setting a 'set' attribute, to give in a set with your applyService:
```
icinga2_applyservice 'areca' do
set 'areca => config in host.vars.areca'
...
end
```
This would result in an applyService config looking like this:
```
apply Service for (areca => config in host.vars.areca) {
...
}
```
The 'set' attribute expects a regex in the format of `/^[a-z]+\s=>\s[a-z]+\sin\s\S+$/`.
> Add set attribute to support 'apply Service for'

- libraries/icinga2.rb
- templates/default/object.applyservice.conf.erb
Closes [9367](https://dev.icinga.org/issues/9367).
Adds a method that will not inspect a string if it contains a `+` sign. A `+` sign implies string concatenation and concatenation will not work if the var gets an inspected.
> Adds evaluate_quotes method in favor of inspect

- README.md
- resources/environment.rb
The host_display_name_attr is restricted to only fqdn and hostname
attributes of a node, only these could be used to name a host in icinga2.
This commit adds another option - a node name, under which is a node
registered within chef server.
For me this is useful, because nor fqdn or hostname are not really
descriptive and can't/won't change it. But I can use the chef node name,
which is under my control, nice and descriptive.
> Node name added as a option for host display name

- resources/checkcommand.rb
making command not a required arg as this lwrp is also used for check command templates.  Also the (chef-icinga2) documentation states this is supposed to be an optional argument.
> correct bug in LWRP icinga2_checkcommand to not require command for templates

- libraries/icinga2.rb
- providers/applynotification.rb
- providers/applyservice.rb
- providers/checkcommand.rb
- providers/environment.rb
- providers/host.rb
- providers/notification.rb
- providers/notificationcommand.rb
- providers/service.rb
- providers/timeperiod.rb
- providers/user.rb
- providers/usergroup.rb
- resources/applynotification.rb
- resources/user.rb
- templates/default/object.applyservice.conf.erb
- templates/default/object.checkcommand.conf.erb
- templates/default/object.environment.conf.erb
- templates/default/object.host.conf.erb
- templates/default/object.notificationcommand.conf.erb
- templates/default/object.service.conf.erb
- templates/default/object.timeperiod.conf.erb
- templates/default/object.user.conf.erb
- templates/default/object.usergroup.conf.erb
Hello,
I'm using chef and chef-icinga2 cookbook to generate the configuration for our monitoring. It's great, it works very good, thanks for all your work!
We have a single master (HA will come soon), a few satellite icinga instances and plenty of remote clients, the whole cluster will grow over a time.
I like the idea of configuration sync in Icinga2, by putting the configuration files into zones.d/zone_name/.
Unfortunatelly, this was not possible with the chef-icinga2 cookbook, so I tried to add support for it.
You just have to set the "zone" attribute of a LWRP to the zone name and then the configuration is placed into a config file in zones.d/zone_name/, instead of objects.d.
The "zone" attribute has been removed from the LWRP templates, as it doesn't do anything …
> added suport for placing configuration into zones in zones.d

- attributes/server_objects.rb
- recipes/server_object_host.rb
- recipes/server_object_notificationcommand.rb
- recipes/server_object_service.rb
- recipes/server_object_timeperiod.rb
- recipes/server_object_user.rb
- recipes/server_object_usergroup.rb
One more addition to the zone sync feature, I think one would like to put the default server objects created by chef-icinga2 into a global zone.
> Added an option to put the default icinga object into the global zone

- recipes/server_web2.rb
Every time chef runs it cuts off writes to the file log
```
icingaweb2[29906]: Cannot write to log file "/var/log/icingaweb2/icingaweb2.log" (SplFileObject::__construct(/var/log/icingaweb2/icingaweb2.log): failed to open stream: Permission denied)
```
> cookbook uses invalid/non-functional mode for log directory

- templates/default/object.timeperiod.conf.erb
Without this change you get
````
/etc/icinga2/objects.d/timeperiod.conf(294):   display_name = "U.S. Holidays"
/etc/icinga2/objects.d/timeperiod.conf(295):   ranges = {
/etc/icinga2/objects.d/timeperiod.conf(296):     january 1 = "00:00-24:00"
^
/etc/icinga2/objects.d/timeperiod.conf(297):     monday -1 may = "00:00-24:00"
/etc/icinga2/objects.d/timeperiod.conf(298):     july 4 = "00:00-24:00"
icinga2.service: control process exited, code=exited status=1
Failed to start Icinga host/service/network monitoring system.
Unit icinga2.service entered failed state.
````
> Day names need to be quoted in timeperiod definitions

- attributes/default.rb
- templates/default/icinga2.conf.erb
This is necessary because Icinga2's include_recursive won't follow symlinks.
> Add the ability to include multiple user defined directories.

- libraries/resource_usergroup.rb
- templates/default/object.usergroup.conf.erb
This commit allows the user to pass the `assign_where` statement to the `icinga2_usergroup`-resource.
For example:
```ruby
icinga2_usergroup 'oncall' do
display_name 'On-Call'
assign_where [
'user.vars.isoncall'
]
end
```
Would result in the icinga2 usergroups file containing:
```
[...]
object UserGroup "oncall" {
display_name = "On Call"
assign where user.vars.isoncall
}
[...]
```
I have created an issue with your tracker at: https://dev.icinga.org/issues/10831
> Adds support to use "assign where" in usergroups

- templates/default/object.applynotification.conf.erb
- templates/default/object.notification.conf.erb
The "times"-parameter inside of the configuration blocks to arrange
{apply,}notifications does not allow "-character around the values of
the keys in the hash.
The template used for both these type invokes the #inspect function on
the value of the hash. Always surround the value with double
apostrophes.
This commit fixes that issue.
> The "times"-parameter does not allow "-character

- libraries/icinga2.rb
- spec/unit/helper_spec.rb
- templates/default/object.environment.conf.erb
[Issue 11453](https://dev.icinga.org/issues/11453)
As background, I've been pretty aggressive about dumping lots of Chef node data into host objects. It really reduces the friction of doing fine-grained `assign where` work. After upgrading to Icinga 2.4.4, my templates all broke.
This patch includes a new library function, `icinga_format`, that should do a pretty reasonable job of converting Ruby data into Icinga-language data. My environment searches, with all their node data, seem to work again. I also included some small changes to the template used by environment searches to make my use case go.
That said, I think that most of the templates- and even parts of the template I changed- could use a thorough going-over, and applying of the new `icinga_format` function so that things are …
> Escaping for icinga2_environment host objects 

- recipes/server_apache.rb
- recipes/server_classic_ui.rb
To allow the cookbook to converge successfully on Debian as well as Ubuntu, a number of uses of `node['platform'] == 'ubuntu' `need to be replaced with `node['platform_family'] == 'debian'` as well as adding `debian` into the value_for_platform helper list.
Thanks!
> Debian support

- README.md
- libraries/resource_applyservice.rb
- templates/default/object.applyservice.conf.erb
Add merge_vars attribute to applyservice LWRP to support [3.5.7. Use Object Attributes in Apply Rules](http://docs.icinga.org/icinga2/latest/doc/module/icinga2/chapter/monitoring-basics#using-apply-object-attributes)
Also allows for multiple Service objects to be created from the same set by always using the  icinga2_applyservice resource name in the Service object, rather than only when not using a set e.g.:
http_vhosts_example.com
http_vhost_example.com
Previously, when using the same set with two icinga2_applyservice resources this would only have used the set key as the Service name and created two Service objects named:
example.com
example.com
Please let me know if there is anything else you wish done so this can be merged. Thanks!
> Add merge_vars attribute to applyservice

- recipes/core_config.rb
- templates/default/icinga2.logrotate.erb
Logrotate template should use the `node['icinga2']['user']` and `node['icinga2']['group']` attributes, currently icinga user and group are assumed.
Thanks!
> Add user and group attributes to logrotate template

- libraries/resource_applynotification.rb
As per [Monitoring Basics 3.7.3. Disable Re-notifications](http://docs.icinga.org/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/monitoring-basics#disable-renotification), the regex for interval attribute of applynotification resource should permit 0 as a value in order to allow re-notifications to be disabled.
Thanks!
> Allow re-notifications to be disabled

- libraries/search.rb
Updating rubocop to: `Installing rubocop 0.43.0 (was 0.42.0)`
``` shell
14:37:01 JJs-MacBook-Pro chef-icinga2 > (master) bundle exec rake rubocop
Running RuboCop...
Inspecting 99 files
.............................................................C.....................................
Offenses:
libraries/search.rb:209:30: C: Use safe navigation (&.) instead of checking if an object exists before calling the method.
node_hash['recipes'] = !node.run_list.nil? ? node.run_list.recipes : []
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
libraries/search.rb:210:28: C: Use safe navigation (&.) instead of checking if an object exists before calling the method.
node_hash['roles'] = !node.run_list.nil? ? node.run_list.roles : []
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```
> Rubocop updates

- libraries/resource_envzone.rb
Previously parent variable was missing from template  in icinga2_envzone and thus does not show up in template file.
> Fix missing parent attribute for icinga2_envzone

- recipes/server_os_packages.rb
- recipes/server_web2.rb
Out of the box, Ubuntu 16.04 Xenial does not support installing PHP 5.5. I've updated the versions of the server packages in server_os_packages (specifically for Xenial) to reflect this, and I updated where on disk Icinga looks for the PHP.ini file which, in the case of Xenial using PHP5.6, is at /etc/php/5.6/apache2/php.ini
Because I need this to work in production, I've been applying my changes directly on top of 2.9.1, so I can't say for certain that this all works on the HEAD, but unless some very strange compatibility-breaking changes have been made since then, this code should work fine.
In short, without these changes, running the Icinga cookbook on Ubuntu 16.04 always fails. With these changes, it succeeds, at least for me.
> Ubuntu 16.04 Compatibility updates

- attributes/server_web2.rb
We were having failed Chef runs because the old repository seems to be gone. It looks like this is the new repository used for the web2 interface?
> Updates the web2 git source url

- README.md
- attributes/server_objects.rb
- libraries/provider_environment.rb
- libraries/resource_applyservice.rb
- libraries/resource_environment.rb
- libraries/resource_host.rb
- libraries/resource_service.rb
- templates/default/object.applyservice.conf.erb
- templates/default/object.environment.conf.erb
- templates/default/object.host.conf.erb
- templates/default/object.service.conf.erb
Icinga comes with both a `check_period` and `notification_period`.  We would like to use the latter, so that the checks are run all of the time, but we are only notified of problems during support hours.
I have therefore created a PR with what I think are the required changes - duplicating all lines that have `check_period` in to add `notification_period`.
> Add notification_period by copying check_period

- .kitchen.yml
- libraries/search.rb
If `enable_role_hostgroup` is enabled to generate the hostgroup files, we more than likely want to have hosts that belong to said hostgroup have their roles reported so that the `assign where` works appropriately.
> Add all roles to generated hostgroups for a node

- libraries/resource_applyservice.rb
The current upstream only allows to access hash values when using the extended `apply service` syntax using `set`. I have a use case where I need to iterate over an array, but the resource does not accept this (valid) syntax:
```ruby
icinga2_host "host" do
custom_vars("bar" => ["one", "two"])
end
icinga2_apply_service "svc" do
set 'item in host.vars.bar'
end
```
By adding a quick change to the Regexp, this is now supported
> Allow "item in host.vars.bar" syntax in icinga2_applyservice

- libraries/provider_instance.rb
Without this LWRP did not work at all for me becuase run_context.resource_collection.select would always return an empty object.
Maybe we should add some tests for resources other than the basic installation, too :)
> Fix provider instance

- README.md
- attributes/server_apache.rb
- recipes/server_apache.rb
Current `server_apache.rb` use only htpasswd for user auth. This PR allow to customize Apache templates in wrapper cookbook and add external auth methods like LDAP, PAM, etc.
> Add cookbook for apache conf templates

- templates/default/object.host.conf.erb
- templates/default/object.service.conf.erb
Hello,
Can somebody explain my why `command_endpoint` doesn't have `inspect`? I get errors then I define resource like
```
icinga2_service "testhost_ssh" do
import 'check-service-tmpl-1m'
display_name 'ssh'
host_name testhost
max_check_attempts 4
check_command 'ssh'
zone 'icinga-master'
command_endpoint 'icinga-master'
end
```
> Set command_endpoint inspect

- templates/default/icinga2.service.config.erb
This PR fix /etc/sysconfig/icinga2 for RHEL. Without shell env`ICINGA2_CACHE_DIR` icinga2 init script fails on start. The problem is in `prepare-dirs`:
```
$ /usr/lib/icinga2/prepare-dirs /etc/sysconfig/icinga2
mkdir: missing operand
Try 'mkdir --help' for more information.
chown: missing operand after ‘icinga:icinga’
Try 'chown --help' for more information.
chmod: missing operand after ‘750’
Try 'chmod --help' for more information.
```
icinga2 version
```
icinga2-common-2.7.1-1.el7.icinga.x86_64
```
> Fix icinga2 cache dir

- .kitchen.yml
- attributes/default.rb
- recipes/install.rb
Because of the way the icinga2 repo (at least on apt, but this has also been tested and passed on yum) when trying to install icinga2 and specifying a version, its dependencies try to install newer versions which breaks the install. By installing each dependency one by one with the version pinned, the proper version specified can be installed. All kitchen tests are passing.
> Allow version pinning when installing Icinga2

- LWRP.md
- libraries/resource_idomysqlconnection.rb
- libraries/resource_idopgsqlconnection.rb
- templates/default/object.idomysqlconnection.conf.erb
- templates/default/object.idopgsqlconnection.conf.erb
With the existing `icinga2_idopgsqlconnection` and `icinga2_idomysqlconnection` custom resources, you are unable to set the [`socket_path`](https://www.icinga.com/docs/icinga2/latest/doc/09-object-types/#objecttype-idomysqlconnection) option in the object.
While I was using the [chef-icingaweb2](https://github.com/Icinga/chef-icingaweb2/blob/master/recipes/ido.rb#L113) cookbook, it does not set `socket_path`, so it defaults to `/var/lib/mysql/mysql.sock` when `host` is set to `localhost`.
Users may need to specify where there socket is located if they don't want to open up permissions to `/var/lib/mysql` or they have a non-standard socket path.
Add the `socket_path` variable to both `icinga2_idopgsqlconnection` and `icinga2_idomysqlconnection` custom resources and their templates.
I …
> Feature: add socket_path to `icinga2_idopgsqlconnection` and `icinga2_idomysqlconnection` custom resources
